on:
  push:
    branches:
      - master
      - develop

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A job to test
    steps:
    - name: Test action step
      uses: carloseduard0/gcm-projeto-parte-2@v1
      with:
        github_token: ${{ github.token }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}